function make_tmp_dir()
{
  tempdir=$(mktemp -d /tmp/gnucash-maint-copr.XXXXXX)
  pushd "${tempdir}"
  mkdir -p {BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMSSOURCE}
  mkdir -p RPMS/{i686,x86_64,noarch}
  popd
}

function prepare_repo()
{
  pushd "${repodir}"
  echo "Update repository $repodir"
  git checkout $refspec
  git fetch
  git reset --hard origin/$refspec
  popd
}

function get_versions()
{
  echo "Extracting version numbers for package $package"
  pushd "${repodir}"
  gc_version=$(grep AC_INIT configure.ac | perl -pe 's/.*([0-9]+\.[0-9]+\.[0-9]+).*\)/$1/ge')
  gc_commit=$(git reflog | head -n1 | awk '{print $1}')
  gc_full_version=${gc_version}-nightly.git.${gc_commit}
  popd
}

function create_specfile()
{
  echo "Writing ${package}.spec"
  perl -p -e"s#^Source: .*\$#Source: ${package}-${refspec}.tar.bz2#;" \
          -e"s#^Version: .*\$#Version: $gc_version#;" \
          -e"s#^Release: .*\$#Release: nightly.git.$gc_commit#" ${package}.spec > "${tempdir}/SPECS/${package}.spec"
}

function create_tarball()
{
  echo "Create source tarball ${package}-${refspec}.tar.bz2"
  pushd "${repodir}"
  git archive ${gc_commit} --prefix "${package}-${gc_version}/" > "${tempdir}/SOURCES/${package}-${refspec}.tar"
  popd

  if [[ "$package" = "gnucash" ]]
  then
    echo "Add extra version information via gnc-version.h and gnc-vcs-version.h"
    mkdir -p "${package}-${gc_version}/src/core-utils"
    pushd "${package}-${gc_version}/src/core-utils"
    echo "/* Autogenerated. Do not change. */"   > gnc-version.h
    echo "#ifndef GNC_VERSION_H"                >> gnc-version.h
    echo "#define GNC_VERSION_H"                >> gnc-version.h
    echo ""                                     >> gnc-version.h
    echo "#define GNUCASH_SCM \"git\""          >> gnc-version.h
    echo "#define GNUCASH_BUILD_DATE \"`date +%Y-%m-%d`\"" >> gnc-version.h
    echo "#include \"gnc-vcs-info.h\""          >> gnc-version.h
    echo "#endif"                               >> gnc-version.h

    echo "/* Autogenerated. Do not change. */"     > gnc-vcs-info.h
    echo "#define GNUCASH_SCM_REV \"$gc_commit\"" >> gnc-vcs-info.h
    popd
    
    tar -rvf "${tempdir}/SOURCES/${package}-${refspec}.tar" --owner=root --group=root "${package}-${gc_version}"
    rm -fr "${package}-${gc_version}"
  fi
  
  bzip2 "${tempdir}/SOURCES/${package}-${refspec}.tar"
}

function create_srpm()
{
  echo "Build source rpm ${package}-${gc_full_version}.src.rpm"
  rpmbuild -D"%_topdir ${tempdir}" -bs ${tempdir}/SPECS/${package}.spec
}